language: php
php:
  - 5.5
  - 5.4
  - 5.3
services:
  - mysql
before_script:
  - composer install
  - mysql -e 'create database testdb;'
  - mysql -e 'CREATE TABLE IF NOT EXISTS `testdb`.`Demo` (`key` varchar(255) NOT NULL,`value` text NOT NULL, PRIMARY KEY (`key`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;'
script: vendor/bin/phpunit tests/