<?php
/**
 * Fizz is a lightweight ORM
 *
 * @author Skylar Kelty <skylarkelty@gmail.com>
 */

namespace SkylarK\Fizz\Util;

/**
 * Introspect can be used to grab data from a present database
 */
class Introspect
{
	/** PDO */
	private $_pdo;
	
	/**
	 * Constructor
	 */
	public function __construct() {
		$this->_pdo = \SkylarK\Fizz\FizzConfig::getDB();
	}

	/**
	 * Returns a list of tables in the database
	 *
	 * @return array Array of tables
	 */
	public function getTables() {
		$result = array();

		$stmt = $this->_pdo->query("SHOW TABLES");
		foreach ($stmt as $row) {
			$result[] = $row[0];
		}

		return $result;
	}

	/**
	 * Returns an array of column metadata for a given table
	 *
	 * @param string $table The table to inspect
	 * @return array Array of column metadata
	 */
	public function getMeta($table) {
		$result = array();

		$stmt = $this->_pdo->query("DESCRIBE $table");

		foreach ($stmt as $v) {
			$result[] = array(
				"name" => $v['Field'],
				"type" => $v['Type'],
				"null" => $v['Null'],
				"iskey" => $v['Key'],
				"default" => $v['Default'],
				"extra" => $v['Extra']
			);
		}

		return $result;
	}


	/**
	 * Saves Fizz Models to a directory
	 * 
	 * @param string $directory The directory to write the PHP model's too
	 * @param string $namespace The namespace for each model
	 */
	public function saveModels($directory, $namespace = '') {
		if (!is_writable($directory)) {
			echo "Cannot write to directory!\n";
			return;
		}

		echo "Running Introspector...\n";

		$tables = $this->getTables();

		if (empty($tables)) {
			die("No tables found.\n");
		}

		$count = count($tables);
		echo "Found $count tables...\n";

		foreach ($tables as $table) {
			echo "Processing $table...\n";

			$meta = $this->getMeta($table);

			// Support PSR-0 autoloading
			$tClass = str_replace("_", " ", $table);
			$tClass = ucwords($tClass);
			$tClass = str_replace(" ", "", $tClass);

			$file = "<?php\n";
			$file .= "/**\n";
			$file .= " * Automatically generated by Fizz-Introspect\n";
			$file .= " * \n";
			$file .= " * @version " . strftime("%H:%M %d-%m-%Y") . "\n";
			$file .= " * @author Fizz-Introspect\n";
			$file .= " */\n";
			$file .= "\n";
			if (!empty($namespace)) {
				$file .= "namespace $namespace;\n";
			}
			$file .= "\n";
			$file .= "/**\n";
			$file .= " * Fizz Model $tClass for table $table\n";
			$file .= " */\n";
			$file .= "class $tClass extends \SkylarK\Fizz\Fizz\n";
			$file .= "{\n";
			
			// Print vars
			foreach ($meta as $column) {
				$file .= "\tpublic \${$column['name']};\n";
			}

			// Override this method for slightly improved speed
			$file .= "\n";
			$file .= "\t/**\n";
			$file .= "\t * Returns the table name\n";
			$file .= "\t */\n";
			$file .= "\tpublic static function tablename() {\n";
			$file .= "\t\treturn '$table';\n";
			$file .= "\t}\n";

			$file .= "}\n";

			$filename =  "$directory/$tClass.php";

			$f = fopen($filename, "w+");
			if ($f) {
				fwrite($f, $file);
				fclose($f);
			}
		}
	}


	/**
	 * Prints Fizz Models
	 */
	public function printModels() {
		echo "Running Introspector...\n";

		$tables = $this->getTables();

		if (empty($tables)) {
			die("No tables found.\n");
		}

		foreach ($tables as $table) {
			$meta = $this->getMeta($table);

			echo "class $table extends SkylarK\Fizz\Fizz\n";
			echo "{\n";
			foreach ($meta as $column) {
				echo "\tpublic \${$column['name']};\n";
			}
			echo "}\n";
		}
	}
}